### ISSUE TITLE
API Test Reports are incorrectly formatted for some endpoints

### ISSUE THREAD

**Issue by hfunsh** [Coveros/selenified#108] opened 2018-10-06 22:47 UTC
When running API tests against certain endpoints, the "**Actual Result**" column of the HTML reports does not line up with the rest of the table. 

Here's an example of one such endpoint along with a code snippet and screenshots of the reports. 
https://api.github.com/users/johndoe

 ```
@BeforeClass(alwaysRun = true)
    public void beforeClass(ITestContext test) {
      setTestSite(this, test, "https://api.github.com/users/johndoe");  
      setAuthor(this, test, "Hammid Funsho\n<br/>hammidfunsho@gmail.com");
      setVersion(this, test, "0.0.1");
    }
   @Test(groups = { "services" }, description = "A sample services test to verify the response code")
    public void sampleServicesCityTest() {
        Call call = this.calls.get();
        Response response = call.get("");
        response.assertEquals(200);
        response.assertContains("johndoe");
        finish();
    }
```

![screen shot 2018-10-06 at 6 20 30 pm](https://user-images.githubusercontent.com/5298345/46576421-f6576480-c996-11e8-8093-0c0ea58f3f8e.png)
![screen shot 2018-10-06 at 6 21 36 pm](https://user-images.githubusercontent.com/5298345/46576457-c492cd80-c997-11e8-84ee-436b4311c776.png)
![screen shot 2018-10-06 at 6 21 49 pm](https://user-images.githubusercontent.com/5298345/46576463-d1afbc80-c997-11e8-9d0b-1077571933ee.png)

Note: This appears to only affect certain endpoint

**Comment by msaperst** [comment] 2018-10-09 18:02
Hammid, I don't understand what you're seeing as an issue. Can you attach the html report? Or the test case? The image you send seems just fine to me

**Comment by msaperst** [comment] 2019-01-07 15:14
@hfunsh can you please update? I can't reproduce this

**Comment by hfunsh** [comment] 2019-01-07 23:40
Apologies for the late response @msaperst , I've attached the report.
 You'll have to rename to .html (github wouldn't accept html file). 

The issue is that the "Actual Results" column stretches out beyond the rest of the page. This means a user has to scroll sideways (quite a bit) in order to see the entire column. 
You can see it in my original screenshot above, along with the code used to reproduce it......be sure to use this endpoint https://api.github.com/users/johndoe

Feel free to close ticket if you're unable to reproduce still....might just be specific to my OS (OSX)
Thanks
[apitests_APITests_sampleServicesCityTestNONE.txt](https://github.com/Coveros/selenified/files/2734661/apitests_APITests_sampleServicesCityTestNONE.txt)

**Comment by msaperst** [comment] 2019-04-04 19:25
@hfunsh I'm still not following exactly what the issue is. Is this just a usability issue, with a desire to have the json formatted prettily?

**Comment by msaperst** [comment] 2019-08-12 18:45
@hfunsh any more updates on this? Otherwise I'm going to close this issue

**Comment by hfunsh** [comment] 2019-08-14 15:48
No updates, feel free to close.

**Comment by msaperst** [comment] 2019-08-14 21:20
Closing issue

**Closed by msaperst** 2019-08-14 21:20 UTC
